version: "3.5"
services:
  go_api_web:
    platform: linux/amd64
    container_name: go_api_web
    build: 
      context: ./.docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_api_web
    ports:
      - "3320:3306"
    volumes:
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
